clear; clc; close all;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%% GET BCE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

bce_L1_16bit_GPS_TDPB = load('/home/altboc/c1/test/16bit/bce/TDPB/ecef.sol');
[bce_L1_16bit_GPS_TDPB_std] = getError_new_TDPB(bce_L1_16bit_GPS_TDPB);
truth_t = getTruth_new(bce_L1_16bit_GPS_TDPB);

bce_L1_16bit_GPS_TDCS = load('/home/altboc/c1/test/16bit/bce/TDCS/ecef.sol');
[bce_L1_16bit_GPS_TDCS_std] = getError_new(truth_t, bce_L1_16bit_GPS_TDCS);

bce_L1_16bit_GPS_FDCS = load('/home/altboc/c1/test/16bit/bce/FDCS/ecef.sol');
[bce_L1_16bit_GPS_FDCS_std] = getError_new(truth_t, bce_L1_16bit_GPS_FDCS);

bce_L1_16bit_GPS_FDPB = load('/home/altboc/c1/test/16bit/bce/FDPB/ecef.sol');
[bce_L1_16bit_GPS_FDPB_std] = getError_new(truth_t, bce_L1_16bit_GPS_FDPB);

bce_L1_16bit_GPS_NoMit = load('/home/altboc/c1/test/16bit/bce/NoMit/ecef.sol');
[bce_L1_16bit_GPS_NoMit_std] = getError_new(truth_t, bce_L1_16bit_GPS_NoMit);

bce_L1_8Bit_GPS_TDCS = load('/home/altboc/c1/test/8Bit/bce/TDCS/ecef.sol');
[bce_L1_8Bit_GPS_TDCS_std] = getError_new(truth_t, bce_L1_16bit_GPS_TDCS);

bce_L1_8Bit_GPS_TDPB = load('/home/altboc/c1/test/8Bit/bce/TDPB/ecef.sol');
[bce_L1_8Bit_GPS_TDPB_std] = getError_new(truth_t, bce_L1_16bit_GPS_TDPB);

bce_L1_8Bit_GPS_FDCS = load('/home/altboc/c1/test/8Bit/bce/FDCS/ecef.sol');
[bce_L1_8Bit_GPS_FDCS_std] = getError_new(truth_t, bce_L1_16bit_GPS_FDCS);

bce_L1_8Bit_GPS_FDPB = load('/home/altboc/c1/test/8Bit/bce/FDPB/ecef.sol');
[bce_L1_8Bit_GPS_FDPB_std] = getError_new(truth_t, bce_L1_16bit_GPS_FDPB);

bce_L1_8Bit_GPS_NoMit = load('/home/altboc/c1/test/8Bit/bce/NoMit/ecef.sol');
[bce_L1_8Bit_GPS_NoMit_std] = getError_new(truth_t, bce_L1_16bit_GPS_NoMit);

% BCE Hor
dataset = {'L1_8Bit_GPS_TDCS';'L1_16bit_GPS_TDCS'; ...
           'L1_8Bit_GPS_TDPB';'L1_16bit_GPS_TDPB'; ...
           'L1_8Bit_GPS_FDCS';'L1_16bit_GPS_FDCS'; ...
           'L1_8Bit_GPS_FDPB';'L1_16bit_GPS_FDPB'; ...
           'L1_8Bit_GPS_NoMit';'L1_16bit_GPS_NoMit'};
med_ = [median(bce_L1_8Bit_GPS_TDCS_std); median(bce_L1_16bit_GPS_TDCS_std); ...
        median(bce_L1_8Bit_GPS_TDPB_std); median(bce_L1_16bit_GPS_TDPB_std); ...
        median(bce_L1_8Bit_GPS_FDCS_std); median(bce_L1_16bit_GPS_FDCS_std); ...
        median(bce_L1_8Bit_GPS_FDPB_std); median(bce_L1_16bit_GPS_FDPB_std); ...
        median(bce_L1_8Bit_GPS_NoMit_std); median(bce_L1_16bit_GPS_NoMit_std)];
mean_ = [mean(bce_L1_8Bit_GPS_TDCS_std); mean(bce_L1_16bit_GPS_TDCS_std); ...
         mean(bce_L1_8Bit_GPS_TDPB_std); mean(bce_L1_16bit_GPS_TDPB_std); ...
         mean(bce_L1_8Bit_GPS_FDCS_std); mean(bce_L1_16bit_GPS_FDCS_std); ...
         mean(bce_L1_8Bit_GPS_FDPB_std); mean(bce_L1_16bit_GPS_FDPB_std); ...
         mean(bce_L1_8Bit_GPS_NoMit_std); mean(bce_L1_16bit_GPS_NoMit_std)];
var_ = [var(bce_L1_8Bit_GPS_TDCS_std); var(bce_L1_16bit_GPS_TDCS_std); ...
        var(bce_L1_8Bit_GPS_TDPB_std); var(bce_L1_16bit_GPS_TDPB_std); ...
        var(bce_L1_8Bit_GPS_FDCS_std); var(bce_L1_16bit_GPS_FDCS_std); ...
        var(bce_L1_8Bit_GPS_FDPB_std); var(bce_L1_16bit_GPS_FDPB_std); ...
        var(bce_L1_8Bit_GPS_NoMit_std); var(bce_L1_16bit_GPS_NoMit_std)];
max_ = [max(bce_L1_8Bit_GPS_TDCS_std); max(bce_L1_16bit_GPS_TDCS_std); ...
        max(bce_L1_8Bit_GPS_TDPB_std); max(bce_L1_16bit_GPS_TDPB_std); ...
        max(bce_L1_8Bit_GPS_FDCS_std); max(bce_L1_16bit_GPS_FDCS_std); ...
        max(bce_L1_8Bit_GPS_FDPB_std); max(bce_L1_16bit_GPS_FDPB_std); ...
        max(bce_L1_8Bit_GPS_NoMit_std); max(bce_L1_16bit_GPS_NoMit_std)];

Batch_Covariance_Results = table(dataset,med_, mean_, var_, max_)
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%% GET L2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

l2_L1_16bit_GPS_TDPB = load('/home/altboc/c1/test/16bit/l2/TDPB/ecef.sol');
[l2_L1_16bit_GPS_TDPB_std] = getError_new_TDPB(l2_L1_16bit_GPS_TDPB);
truth_t = getTruth_new(l2_L1_16bit_GPS_TDPB);

l2_L1_16bit_GPS_TDCS = load('/home/altboc/c1/test/16bit/l2/TDCS/ecef.sol');
[l2_L1_16bit_GPS_TDCS_std] = getError_new(truth_t, l2_L1_16bit_GPS_TDCS);

l2_L1_16bit_GPS_FDCS = load('/home/altboc/c1/test/16bit/l2/FDCS/ecef.sol');
[l2_L1_16bit_GPS_FDCS_std] = getError_new(truth_t, l2_L1_16bit_GPS_FDCS);

l2_L1_16bit_GPS_FDPB = load('/home/altboc/c1/test/16bit/l2/FDPB/ecef.sol');
[l2_L1_16bit_GPS_FDPB_std] = getError_new(truth_t, l2_L1_16bit_GPS_FDPB);

l2_L1_16bit_GPS_NoMit = load('/home/altboc/c1/test/16bit/l2/NoMit/ecef.sol');
[l2_L1_16bit_GPS_NoMit_std] = getError_new(truth_t, l2_L1_16bit_GPS_NoMit);

l2_L1_8Bit_GPS_TDCS = load('/home/altboc/c1/test/8Bit/l2/TDCS/ecef.sol');
[l2_L1_8Bit_GPS_TDCS_std] = getError_new(truth_t, l2_L1_16bit_GPS_TDCS);

l2_L1_8Bit_GPS_TDPB = load('/home/altboc/c1/test/8Bit/l2/TDPB/ecef.sol');
[l2_L1_8Bit_GPS_TDPB_std] = getError_new(truth_t, l2_L1_16bit_GPS_TDPB);

l2_L1_8Bit_GPS_FDCS = load('/home/altboc/c1/test/8Bit/l2/FDCS/ecef.sol');
[l2_L1_8Bit_GPS_FDCS_std] = getError_new(truth_t, l2_L1_16bit_GPS_FDCS);

l2_L1_8Bit_GPS_FDPB = load('/home/altboc/c1/test/8Bit/l2/FDPB/ecef.sol');
[l2_L1_8Bit_GPS_FDPB_std] = getError_new(truth_t, l2_L1_16bit_GPS_FDPB);

l2_L1_8Bit_GPS_NoMit = load('/home/altboc/c1/test/8Bit/l2/NoMit/ecef.sol');
[l2_L1_8Bit_GPS_NoMit_std] = getError_new(truth_t, l2_L1_16bit_GPS_NoMit);



% L2 Hor
dataset = {'L1_8Bit_GPS_TDCS';'L1_16bit_GPS_TDCS'; ...
           'L1_8Bit_GPS_TDPB';'L1_16bit_GPS_TDPB'; ...
           'L1_8Bit_GPS_FDCS';'L1_16bit_GPS_FDCS'; ...
           'L1_8Bit_GPS_FDPB';'L1_16bit_GPS_FDPB'; ...
           'L1_8Bit_GPS_NoMit';'L1_16bit_GPS_NoMit'};
med_ = [median(l2_L1_8Bit_GPS_TDCS_std); median(l2_L1_16bit_GPS_TDCS_std); ...
        median(l2_L1_8Bit_GPS_TDPB_std); median(l2_L1_16bit_GPS_TDPB_std); ...
        median(l2_L1_8Bit_GPS_FDCS_std); median(l2_L1_16bit_GPS_FDCS_std); ...
        median(l2_L1_8Bit_GPS_FDPB_std); median(l2_L1_16bit_GPS_FDPB_std); ...
        median(l2_L1_8Bit_GPS_NoMit_std); median(l2_L1_16bit_GPS_NoMit_std)];
mean_ = [mean(l2_L1_8Bit_GPS_TDCS_std); mean(l2_L1_16bit_GPS_TDCS_std); ...
         mean(l2_L1_8Bit_GPS_TDPB_std); mean(l2_L1_16bit_GPS_TDPB_std); ...
         mean(l2_L1_8Bit_GPS_FDCS_std); mean(l2_L1_16bit_GPS_FDCS_std); ...
         mean(l2_L1_8Bit_GPS_FDPB_std); mean(l2_L1_16bit_GPS_FDPB_std); ...
         mean(l2_L1_8Bit_GPS_NoMit_std); mean(l2_L1_16bit_GPS_NoMit_std)];
var_ = [var(l2_L1_8Bit_GPS_TDCS_std); var(l2_L1_16bit_GPS_TDCS_std); ...
        var(l2_L1_8Bit_GPS_TDPB_std); var(l2_L1_16bit_GPS_TDPB_std); ...
        var(l2_L1_8Bit_GPS_FDCS_std); var(l2_L1_16bit_GPS_FDCS_std); ...
        var(l2_L1_8Bit_GPS_FDPB_std); var(l2_L1_16bit_GPS_FDPB_std); ...
        var(l2_L1_8Bit_GPS_NoMit_std); var(l2_L1_16bit_GPS_NoMit_std)];
max_ = [max(l2_L1_8Bit_GPS_TDCS_std); max(l2_L1_16bit_GPS_TDCS_std); ...
        max(l2_L1_8Bit_GPS_TDPB_std); max(l2_L1_16bit_GPS_TDPB_std); ...
        max(l2_L1_8Bit_GPS_FDCS_std); max(l2_L1_16bit_GPS_FDCS_std); ...
        max(l2_L1_8Bit_GPS_FDPB_std); max(l2_L1_16bit_GPS_FDPB_std); ...
        max(l2_L1_8Bit_GPS_NoMit_std); max(l2_L1_16bit_GPS_NoMit_std)];

L2_Results = table(dataset,med_, mean_, var_, max_)

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%% GET DCS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dcs_L1_16bit_GPS_TDPB = load('/home/altboc/c1/test/16bit/dcs/TDPB/ecef.sol');
[dcs_L1_16bit_GPS_TDPB_std] = getError_new_TDPB(dcs_L1_16bit_GPS_TDPB);
truth_t = getTruth_new(dcs_L1_16bit_GPS_TDPB);

dcs_L1_16bit_GPS_TDCS = load('/home/altboc/c1/test/16bit/dcs/TDCS/ecef.sol');
[dcs_L1_16bit_GPS_TDCS_std] = getError_new(truth_t, dcs_L1_16bit_GPS_TDCS);

dcs_L1_16bit_GPS_FDCS = load('/home/altboc/c1/test/16bit/dcs/FDCS/ecef.sol');
[dcs_L1_16bit_GPS_FDCS_std] = getError_new(truth_t, dcs_L1_16bit_GPS_FDCS);

dcs_L1_16bit_GPS_FDPB = load('/home/altboc/c1/test/16bit/dcs/FDPB/ecef.sol');
[dcs_L1_16bit_GPS_FDPB_std] = getError_new(truth_t, dcs_L1_16bit_GPS_FDPB);

dcs_L1_16bit_GPS_NoMit = load('/home/altboc/c1/test/16bit/dcs/NoMit/ecef.sol');
[dcs_L1_16bit_GPS_NoMit_std] = getError_new(truth_t, dcs_L1_16bit_GPS_NoMit);

dcs_L1_8Bit_GPS_TDCS = load('/home/altboc/c1/test/8Bit/dcs/TDCS/ecef.sol');
[dcs_L1_8Bit_GPS_TDCS_std] = getError_new(truth_t, dcs_L1_16bit_GPS_TDCS);

dcs_L1_8Bit_GPS_TDPB = load('/home/altboc/c1/test/8Bit/dcs/TDPB/ecef.sol');
[dcs_L1_8Bit_GPS_TDPB_std] = getError_new(truth_t, dcs_L1_16bit_GPS_TDPB);

dcs_L1_8Bit_GPS_FDCS = load('/home/altboc/c1/test/8Bit/dcs/FDCS/ecef.sol');
[dcs_L1_8Bit_GPS_FDCS_std] = getError_new(truth_t, dcs_L1_16bit_GPS_FDCS);

dcs_L1_8Bit_GPS_FDPB = load('/home/altboc/c1/test/8Bit/dcs/FDPB/ecef.sol');
[dcs_L1_8Bit_GPS_FDPB_std] = getError_new(truth_t, dcs_L1_16bit_GPS_FDPB);

dcs_L1_8Bit_GPS_NoMit = load('/home/altboc/c1/test/8Bit/dcs/NoMit/ecef.sol');
[dcs_L1_8Bit_GPS_NoMit_std] = getError_new(truth_t, dcs_L1_16bit_GPS_NoMit);


% DCS Hor
dataset = {'L1_8Bit_GPS_TDCS';'L1_16bit_GPS_TDCS'; ...
           'L1_8Bit_GPS_TDPB';'L1_16bit_GPS_TDPB'; ...
           'L1_8Bit_GPS_FDCS';'L1_16bit_GPS_FDCS'; ...
           'L1_8Bit_GPS_FDPB';'L1_16bit_GPS_FDPB'; ...
           'L1_8Bit_GPS_NoMit';'L1_16bit_GPS_NoMit'};
med_ = [median(dcs_L1_8Bit_GPS_TDCS_std); median(dcs_L1_16bit_GPS_TDCS_std); ...
        median(dcs_L1_8Bit_GPS_TDPB_std); median(dcs_L1_16bit_GPS_TDPB_std); ...
        median(dcs_L1_8Bit_GPS_FDCS_std); median(dcs_L1_16bit_GPS_FDCS_std); ...
        median(dcs_L1_8Bit_GPS_FDPB_std); median(dcs_L1_16bit_GPS_FDPB_std); ...
        median(dcs_L1_8Bit_GPS_NoMit_std); median(dcs_L1_16bit_GPS_NoMit_std)];
mean_ = [mean(dcs_L1_8Bit_GPS_TDCS_std); mean(dcs_L1_16bit_GPS_TDCS_std); ...
         mean(dcs_L1_8Bit_GPS_TDPB_std); mean(dcs_L1_16bit_GPS_TDPB_std); ...
         mean(dcs_L1_8Bit_GPS_FDCS_std); mean(dcs_L1_16bit_GPS_FDCS_std); ...
         mean(dcs_L1_8Bit_GPS_FDPB_std); mean(dcs_L1_16bit_GPS_FDPB_std); ...
         mean(dcs_L1_8Bit_GPS_NoMit_std); mean(dcs_L1_16bit_GPS_NoMit_std)];
var_ = [var(dcs_L1_8Bit_GPS_TDCS_std); var(dcs_L1_16bit_GPS_TDCS_std); ...
        var(dcs_L1_8Bit_GPS_TDPB_std); var(dcs_L1_16bit_GPS_TDPB_std); ...
        var(dcs_L1_8Bit_GPS_FDCS_std); var(dcs_L1_16bit_GPS_FDCS_std); ...
        var(dcs_L1_8Bit_GPS_FDPB_std); var(dcs_L1_16bit_GPS_FDPB_std); ...
        var(dcs_L1_8Bit_GPS_NoMit_std); var(dcs_L1_16bit_GPS_NoMit_std)];
max_ = [max(dcs_L1_8Bit_GPS_TDCS_std); max(dcs_L1_16bit_GPS_TDCS_std); ...
        max(dcs_L1_8Bit_GPS_TDPB_std); max(dcs_L1_16bit_GPS_TDPB_std); ...
        max(dcs_L1_8Bit_GPS_FDCS_std); max(dcs_L1_16bit_GPS_FDCS_std); ...
        max(dcs_L1_8Bit_GPS_FDPB_std); max(dcs_L1_16bit_GPS_FDPB_std); ...
        max(dcs_L1_8Bit_GPS_NoMit_std); max(dcs_L1_16bit_GPS_NoMit_std)];

DCS_Results = table(dataset,med_, mean_, var_, max_)

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%% GET MM %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
mm_L1_16bit_GPS_TDPB = load('/home/altboc/c1/test/16bit/mm/TDPB/ecef.sol');
[mm_L1_16bit_GPS_TDPB_std] = getError_new_TDPB(mm_L1_16bit_GPS_TDPB);
truth_t = getTruth_new(mm_L1_16bit_GPS_TDPB);

mm_L1_16bit_GPS_TDCS = load('/home/altboc/c1/test/16bit/mm/TDCS/ecef.sol');
[mm_L1_16bit_GPS_TDCS_std] = getError_new(truth_t, mm_L1_16bit_GPS_TDCS);

mm_L1_16bit_GPS_FDCS = load('/home/altboc/c1/test/16bit/mm/FDCS/ecef.sol');
[mm_L1_16bit_GPS_FDCS_std] = getError_new(truth_t, mm_L1_16bit_GPS_FDCS);

mm_L1_16bit_GPS_FDPB = load('/home/altboc/c1/test/16bit/mm/FDPB/ecef.sol');
[mm_L1_16bit_GPS_FDPB_std] = getError_new(truth_t, mm_L1_16bit_GPS_FDPB);

mm_L1_16bit_GPS_NoMit = load('/home/altboc/c1/test/16bit/mm/NoMit/ecef.sol');
[mm_L1_16bit_GPS_NoMit_std] = getError_new(truth_t, mm_L1_16bit_GPS_NoMit);

mm_L1_8Bit_GPS_TDCS = load('/home/altboc/c1/test/8Bit/mm/TDCS/ecef.sol');
[mm_L1_8Bit_GPS_TDCS_std] = getError_new(truth_t, mm_L1_16bit_GPS_TDCS);

mm_L1_8Bit_GPS_TDPB = load('/home/altboc/c1/test/8Bit/mm/TDPB/ecef.sol');
[mm_L1_8Bit_GPS_TDPB_std] = getError_new(truth_t, mm_L1_16bit_GPS_TDPB);

mm_L1_8Bit_GPS_FDCS = load('/home/altboc/c1/test/8Bit/mm/FDCS/ecef.sol');
[mm_L1_8Bit_GPS_FDCS_std] = getError_new(truth_t, mm_L1_16bit_GPS_FDCS);

mm_L1_8Bit_GPS_FDPB = load('/home/altboc/c1/test/8Bit/mm/FDPB/ecef.sol');
[mm_L1_8Bit_GPS_FDPB_std] = getError_new(truth_t, mm_L1_16bit_GPS_FDPB);

mm_L1_8Bit_GPS_NoMit = load('/home/altboc/c1/test/8Bit/mm/NoMit/ecef.sol');
[mm_L1_8Bit_GPS_NoMit_std] = getError_new(truth_t, mm_L1_16bit_GPS_NoMit);



% mm Hor
dataset = {'L1_8Bit_GPS_TDCS';'L1_16bit_GPS_TDCS'; ...
           'L1_8Bit_GPS_TDPB';'L1_16bit_GPS_TDPB'; ...
           'L1_8Bit_GPS_FDCS';'L1_16bit_GPS_FDCS'; ...
           'L1_8Bit_GPS_FDPB';'L1_16bit_GPS_FDPB'; ...
           'L1_8Bit_GPS_NoMit';'L1_16bit_GPS_NoMit'};
med_ = [median(mm_L1_8Bit_GPS_TDCS_std); median(mm_L1_16bit_GPS_TDCS_std); ...
        median(mm_L1_8Bit_GPS_TDPB_std); median(mm_L1_16bit_GPS_TDPB_std); ...
        median(mm_L1_8Bit_GPS_FDCS_std); median(mm_L1_16bit_GPS_FDCS_std); ...
        median(mm_L1_8Bit_GPS_FDPB_std); median(mm_L1_16bit_GPS_FDPB_std); ...
        median(mm_L1_8Bit_GPS_NoMit_std); median(mm_L1_16bit_GPS_NoMit_std)];
mean_ = [mean(mm_L1_8Bit_GPS_TDCS_std); mean(mm_L1_16bit_GPS_TDCS_std); ...
         mean(mm_L1_8Bit_GPS_TDPB_std); mean(mm_L1_16bit_GPS_TDPB_std); ...
         mean(mm_L1_8Bit_GPS_FDCS_std); mean(mm_L1_16bit_GPS_FDCS_std); ...
         mean(mm_L1_8Bit_GPS_FDPB_std); mean(mm_L1_16bit_GPS_FDPB_std); ...
         mean(mm_L1_8Bit_GPS_NoMit_std); mean(mm_L1_16bit_GPS_NoMit_std)];
var_ = [var(mm_L1_8Bit_GPS_TDCS_std); var(mm_L1_16bit_GPS_TDCS_std); ...
        var(mm_L1_8Bit_GPS_TDPB_std); var(mm_L1_16bit_GPS_TDPB_std); ...
        var(mm_L1_8Bit_GPS_FDCS_std); var(mm_L1_16bit_GPS_FDCS_std); ...
        var(mm_L1_8Bit_GPS_FDPB_std); var(mm_L1_16bit_GPS_FDPB_std); ...
        var(mm_L1_8Bit_GPS_NoMit_std); var(mm_L1_16bit_GPS_NoMit_std)];
max_ = [max(mm_L1_8Bit_GPS_TDCS_std); max(mm_L1_16bit_GPS_TDCS_std); ...
        max(mm_L1_8Bit_GPS_TDPB_std); max(mm_L1_16bit_GPS_TDPB_std); ...
        max(mm_L1_8Bit_GPS_FDCS_std); max(mm_L1_16bit_GPS_FDCS_std); ...
        max(mm_L1_8Bit_GPS_FDPB_std); max(mm_L1_16bit_GPS_FDPB_std); ...
        max(mm_L1_8Bit_GPS_NoMit_std); max(mm_L1_16bit_GPS_NoMit_std)];
    
mm_Results = table(dataset,med_, mean_, var_, max_)
