language: cpp
dist: trusty
sudo: required

addons:
    apt:
        packages:
            - cmake
            - python3
            - python3-dev
            - libeigen3-dev
            - libboost-all-dev
            - libboost-python-dev
            - python3-numpy

install:
    - cd /usr/lib/x86_64-linux-gnu/
    - sudo ln -s libboost_python-py34.so libboost_python3.so
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake -DBUILD_PYTHON_INTERFACE=ON -DBUILD_USE_PYTHON3=ON ..
    - make
    - sudo make install

script:
    - cd $TRAVIS_BUILD_DIR/build
    - ./cluster_test
    - ./scluster_test
    - ./mcluster_test
    - sudo ldconfig
    - cd ../python
    - python3 testapi.py
